spring.application.name=demo-h2

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.platform=h2

# Habilita la ruta: localhost:8080/h2-console
spring.h2.console.enabled=true

# Actualiza automáticamente el esquema de la base de datos, sin borrar datos
spring.jpa.hibernate.ddl-auto=create

# Garantiza que los scripts SQL "schema.sql" se ejecuten después de que JPA haya creado las tablas, evitando errores
spring.jpa.defer-datasource-initialization=true

logging.level.root:INFO
logging.level.com.example.h2:INFO
logging.pattern.console:'%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
